-- Agent Actions Table
-- Stores all actions generated by agents with their status and results

CREATE TABLE IF NOT EXISTS agent_actions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  agent_name TEXT NOT NULL,
  action_id TEXT NOT NULL,
  action_type TEXT NOT NULL,
  priority TEXT NOT NULL,
  
  title TEXT NOT NULL,
  description TEXT,
  action TEXT,
  
  -- Action metadata
  keyword TEXT,
  content_id TEXT,
  competitor TEXT,
  campaign TEXT,
  platform TEXT,
  target_page TEXT,
  
  -- Expected outcome
  expected_outcome JSONB,
  
  -- Status tracking
  status TEXT NOT NULL DEFAULT 'pending',
  
  -- Execution tracking
  executed_at TIMESTAMPTZ,
  execution_result JSONB,
  error_message TEXT,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  CONSTRAINT agent_actions_status_check CHECK (status IN ('pending', 'executing', 'completed', 'failed', 'skipped')),
  CONSTRAINT agent_actions_priority_check CHECK (priority IN ('critical', 'high', 'medium', 'low'))
);

CREATE INDEX idx_agent_actions_agent_name ON agent_actions(agent_name, created_at DESC);
CREATE INDEX idx_agent_actions_status ON agent_actions(status, priority);
CREATE INDEX idx_agent_actions_action_id ON agent_actions(action_id);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_agent_actions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER agent_actions_updated_at
  BEFORE UPDATE ON agent_actions
  FOR EACH ROW
  EXECUTE FUNCTION update_agent_actions_updated_at();

COMMENT ON TABLE agent_actions IS 'Stores all actions generated by agents with execution status and results';
