-- Migration 010: GTM Agent Tables
-- Creates tables for ICP analyses, strategies, and cross-system signals
-- Run in Supabase Dashboard → SQL Editor

-- =============================================================================
-- 1. GTM ICP Analyses
-- Stores ICP analysis results from the GTM agent
-- =============================================================================
CREATE TABLE IF NOT EXISTS gtm_icp_analyses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    analysis JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gtm_icp_created_at
    ON gtm_icp_analyses(created_at DESC);

COMMENT ON TABLE gtm_icp_analyses IS 'Stores ICP (Ideal Customer Profile) analyses generated by the GTM agent';

-- =============================================================================
-- 2. GTM Strategies
-- Stores generated GTM strategies with focus area
-- =============================================================================
CREATE TABLE IF NOT EXISTS gtm_strategies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    strategy JSONB NOT NULL,
    focus TEXT NOT NULL DEFAULT 'full',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gtm_strategies_created_at
    ON gtm_strategies(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_gtm_strategies_focus
    ON gtm_strategies(focus);

COMMENT ON TABLE gtm_strategies IS 'Stores GTM strategies (full/content/outreach/ads/expansion) generated by the GTM agent';

-- =============================================================================
-- 3. GTM Signals
-- Stores cross-system signals generated for other agents
-- =============================================================================
CREATE TABLE IF NOT EXISTS gtm_signals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    signals JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gtm_signals_created_at
    ON gtm_signals(created_at DESC);

COMMENT ON TABLE gtm_signals IS 'Stores cross-system signals from GTM agent to SEO/Content/Ads/Social/LinkedIn agents';
