-- Agent Reports Table
-- Stores daily self-reports generated by each agent

CREATE TABLE IF NOT EXISTS agent_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_name TEXT NOT NULL,
  summary TEXT,
  highlights JSONB DEFAULT '[]'::jsonb,
  problems JSONB DEFAULT '[]'::jsonb,
  improvements JSONB DEFAULT '[]'::jsonb,
  ux_suggestions JSONB DEFAULT '[]'::jsonb,
  stats JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast lookups by agent + date
CREATE INDEX IF NOT EXISTS idx_agent_reports_agent_created
  ON agent_reports (agent_name, created_at DESC);

-- RLS
ALTER TABLE agent_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for service role" ON agent_reports FOR ALL USING (true);
