-- 037_content_plan_and_analysis_cache.sql
-- Persistent content plan + cached analysis payloads.
--
-- ── content_plan_items ──────────────────────────────────────────────────────
-- A content idea generated by the agent (or added manually). Lives across
-- sessions so the user can come back to a populated plan, click into each
-- idea, and either expand it to a full article (linking content_piece_id)
-- or keep iterating with the AI editor.
CREATE TABLE IF NOT EXISTS content_plan_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id TEXT NOT NULL DEFAULT 'default',
  title TEXT NOT NULL,
  topic TEXT,
  content_type TEXT NOT NULL DEFAULT 'blog_article',
  target_keyword TEXT,
  pillar TEXT,
  reason TEXT,
  priority TEXT NOT NULL DEFAULT 'medium',     -- 'critical' | 'high' | 'medium' | 'low'
  status TEXT NOT NULL DEFAULT 'idea',         -- 'idea' | 'drafting' | 'draft' | 'published' | 'archived'
  -- When the idea is materialised into a full article, link the row in
  -- content_pieces so the UI can navigate from plan → article and back.
  content_piece_id UUID REFERENCES content_pieces(id) ON DELETE SET NULL,
  source_run_id UUID,                          -- which analysis run produced this idea (nullable)
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_content_plan_items_tenant
  ON content_plan_items(tenant_id);
CREATE INDEX IF NOT EXISTS idx_content_plan_items_status
  ON content_plan_items(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_content_plan_items_created
  ON content_plan_items(tenant_id, created_at DESC);

-- Keep updated_at in sync.
CREATE OR REPLACE FUNCTION set_updated_at_now()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS content_plan_items_updated_at ON content_plan_items;
CREATE TRIGGER content_plan_items_updated_at
  BEFORE UPDATE ON content_plan_items
  FOR EACH ROW EXECUTE FUNCTION set_updated_at_now();

-- ── content_analysis_cache ──────────────────────────────────────────────────
-- One row per (tenant_id, agent) holding the last completed analysis payload.
-- The dashboard reads this on page load so analyses persist between visits
-- instead of disappearing the moment the in-memory cycle status is cleared.
CREATE TABLE IF NOT EXISTS content_analysis_cache (
  tenant_id TEXT NOT NULL DEFAULT 'default',
  agent TEXT NOT NULL DEFAULT 'content',       -- 'content' | 'seo' | 'ads' | ...
  payload JSONB NOT NULL,
  cycle_id TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (tenant_id, agent)
);

CREATE INDEX IF NOT EXISTS idx_content_analysis_cache_created
  ON content_analysis_cache(created_at DESC);

-- Light history of analyses so users can browse past runs without
-- the cache being overwritten. Each completed analysis appends here.
CREATE TABLE IF NOT EXISTS content_analysis_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id TEXT NOT NULL DEFAULT 'default',
  agent TEXT NOT NULL DEFAULT 'content',
  cycle_id TEXT,
  payload JSONB NOT NULL,
  summary JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_content_analysis_history_tenant_agent
  ON content_analysis_history(tenant_id, agent, created_at DESC);
