"""
Inter-Agent Collaboration Chains
Defines event-driven pipelines where one agent's output triggers the next.
"""

import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)


# ── Event Type Constants ─────────────────────────────────────────────────────

EVENT_KEYWORD_GAP_FOUND = "keyword_gap_found"
EVENT_CONTENT_PUBLISHED = "content_published"
EVENT_NEGATIVE_REVIEW = "negative_review_detected"
EVENT_RANKING_DECLINE = "ranking_decline"
EVENT_BUDGET_EXHAUSTED = "budget_exhausted"
EVENT_ANOMALY_DETECTED = "anomaly_detected"
EVENT_CONTENT_DRAFTED = "content_drafted"


# ── Chain Handlers ───────────────────────────────────────────────────────────

async def handle_keyword_gap_found(data: Dict[str, Any]):
    """
    SEO -> Content chain.
    When SEO agent identifies a keyword gap, auto-queue a content draft.
    """
    keyword = data.get("keyword", "")
    gap_type = data.get("gap_type", "blog_post")
    logger.info(f"[chain] keyword_gap_found: '{keyword}' — queuing content draft")

    try:
        from shared.actions_db import save_actions
        actions = [{
            "id": f"chain-content-{keyword[:30].replace(' ', '-')}",
            "type": "content_creation",
            "priority": data.get("priority", "medium"),
            "title": f"Create {gap_type} targeting '{keyword}'",
            "description": (
                f"Auto-generated by SEO->Content chain. "
                f"Keyword '{keyword}' has no matching content."
            ),
            "keyword": keyword,
            "expected_outcome": f"Rank for '{keyword}' within 4 weeks",
            "action": f"Generate {gap_type} draft targeting '{keyword}'",
        }]
        await save_actions("content", actions)
        logger.info(f"[chain] Created content action for keyword '{keyword}'")
    except Exception as e:
        logger.error(f"[chain] Failed to create content action: {e}")


async def handle_content_published(data: Dict[str, Any]):
    """
    Content -> Social chain.
    When content is published, queue social promotion posts.
    """
    title = data.get("title", "")
    url = data.get("url", "")
    logger.info(f"[chain] content_published: '{title}' — queuing social posts")

    try:
        from shared.actions_db import save_actions
        actions = [
            {
                "id": f"chain-social-x-{title[:20].replace(' ', '-')}",
                "type": "social_post",
                "priority": "medium",
                "title": f"Promote on X/Twitter: '{title[:50]}'",
                "description": f"Auto-generated social post for new content: {url}",
                "action": "Generate and queue tweet thread promoting this content",
                "platform": "twitter",
            },
            {
                "id": f"chain-social-li-{title[:20].replace(' ', '-')}",
                "type": "social_post",
                "priority": "medium",
                "title": f"Promote on LinkedIn: '{title[:50]}'",
                "description": f"Auto-generated LinkedIn post for new content: {url}",
                "action": "Generate LinkedIn post promoting this content",
                "platform": "linkedin",
            },
        ]
        await save_actions("social", actions)
        logger.info(f"[chain] Created {len(actions)} social actions for '{title}'")
    except Exception as e:
        logger.error(f"[chain] Failed to create social actions: {e}")


async def handle_ranking_decline(data: Dict[str, Any]):
    """
    SEO -> Content chain.
    When a keyword's ranking declines, flag the content for refresh.
    """
    keyword = data.get("keyword", "")
    url = data.get("url", "")
    logger.info(f"[chain] ranking_decline: '{keyword}' — flagging content refresh")

    try:
        from shared.actions_db import save_actions
        actions = [{
            "id": f"chain-refresh-{keyword[:30].replace(' ', '-')}",
            "type": "content_refresh",
            "priority": "high",
            "title": f"Refresh content for declining keyword '{keyword}'",
            "description": (
                f"Keyword '{keyword}' ranking dropped. "
                f"Page: {url or 'unknown'}. Review and update content."
            ),
            "keyword": keyword,
            "target_page": url,
            "action": "Analyze and refresh content to recover rankings",
        }]
        await save_actions("content", actions)
    except Exception as e:
        logger.error(f"[chain] Failed to create content refresh action: {e}")


async def handle_anomaly_detected(data: Dict[str, Any]):
    """
    Analytics -> Orchestrator chain.
    When an anomaly is detected, create an investigation action.
    """
    metric = data.get("metric", "unknown")
    severity = data.get("severity", "medium")
    logger.info(f"[chain] anomaly_detected: {metric} ({severity})")

    try:
        from shared.actions_db import save_actions
        actions = [{
            "id": f"chain-anomaly-{metric}",
            "type": "investigation",
            "priority": "high" if severity == "critical" else "medium",
            "title": f"Investigate {metric} anomaly",
            "description": data.get("description", f"Anomaly detected in {metric}"),
            "action": "Run cross-channel investigation to identify root cause",
        }]
        await save_actions("analytics", actions)
    except Exception as e:
        logger.error(f"[chain] Failed to create anomaly action: {e}")


async def handle_negative_review(data: Dict[str, Any]):
    """
    Reviews -> Orchestrator chain.
    When a negative review is detected, create an urgent response action
    and notify the team.
    """
    platform = data.get("platform", "unknown")
    rating = data.get("rating", 0)
    logger.info(f"[chain] negative_review_detected: {rating}-star on {platform}")

    try:
        from shared.actions_db import save_actions
        actions = [{
            "id": f"chain-review-respond-{platform}-{rating}",
            "type": "review_response_negative",
            "priority": "critical",
            "title": f"Respond to {rating}-star review on {platform}",
            "description": (
                f"Negative review detected on {platform}. "
                f"Requires a thoughtful, empathetic response within 24 hours."
            ),
            "platform": platform,
            "action": "Draft and queue a professional response to this negative review",
        }]
        await save_actions("reviews", actions)

        # Also send a notification
        from shared.notifications import notification_service
        await notification_service.notify(
            title=f"Negative review on {platform}",
            message=f"{rating}-star review needs a response",
            severity="critical",
            agent="reviews",
        )
    except Exception as e:
        logger.error(f"[chain] Failed to handle negative review: {e}")


async def handle_budget_exhausted(data: Dict[str, Any]):
    """
    Ads -> Analytics chain.
    When a campaign exhausts its budget, trigger an attribution analysis
    to evaluate if the spend was worthwhile.
    """
    campaign = data.get("campaign", "unknown")
    spend = data.get("spend", 0)
    logger.info(f"[chain] budget_exhausted: '{campaign}' spent ${spend}")

    try:
        from shared.actions_db import save_actions
        actions = [{
            "id": f"chain-attribution-{campaign[:30].replace(' ', '-')}",
            "type": "investigation",
            "priority": "high",
            "title": f"Attribution analysis for '{campaign}'",
            "description": (
                f"Campaign '{campaign}' exhausted its budget (${spend}). "
                f"Analyze ROI and determine if budget should be reallocated."
            ),
            "campaign": campaign,
            "action": "Run cross-channel attribution analysis for this campaign",
        }]
        await save_actions("analytics", actions)
    except Exception as e:
        logger.error(f"[chain] Failed to create attribution action: {e}")


# ── Registration ─────────────────────────────────────────────────────────────

async def register_all_chains(event_bus):
    """Register all chain handlers on the event bus."""
    await event_bus.subscribe(EVENT_KEYWORD_GAP_FOUND, handle_keyword_gap_found)
    await event_bus.subscribe(EVENT_CONTENT_PUBLISHED, handle_content_published)
    await event_bus.subscribe(EVENT_RANKING_DECLINE, handle_ranking_decline)
    await event_bus.subscribe(EVENT_ANOMALY_DETECTED, handle_anomaly_detected)
    await event_bus.subscribe(EVENT_NEGATIVE_REVIEW, handle_negative_review)
    await event_bus.subscribe(EVENT_BUDGET_EXHAUSTED, handle_budget_exhausted)
    logger.info("[chains] All 6 inter-agent collaboration chains registered")
