"""
KeywordOpportunityAgent — extracts current keyword targeting from a crawled
site and generates new keyword opportunities to grow organic + AI traffic.

Inputs (provided by SiteAuditAgent):
  - host / base_url: the audited domain.
  - pages: List[PageReport] from the site audit, including titles, H1/H2 text,
    meta descriptions, and a body_text_sample per page.
  - tenant_config: brand_name, competitors, audience, USP — used to bias the
    LLM toward queries the brand actually wants to rank for.

Outputs (a JSON-serialisable dict consumed by the dashboard):
  - current_keywords: phrases the site already targets, with the URLs that
    target them. Built from H1/H2/title/meta + a TF-IDF-ish body extractor.
  - opportunities: new keyword candidates with intent, suggested target URL,
    and rationale. Generated by Claude when available; deterministic fallback
    otherwise.
  - clusters: pillar + supporting keyword groups so the user can plan a
    content topic-cluster strategy instead of one-off blog posts.
  - competitor_gap: best-effort competitor SERP gap when ValueSERP is
    configured; otherwise omitted.
  - related_searches: ValueSERP `related_searches` for the top-extracted
    page topic (free signal of long-tail demand).
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
from collections import Counter
from typing import Any, Dict, List, Optional, Tuple, TYPE_CHECKING
from urllib.parse import urlparse

import httpx

from shared.config import settings

if TYPE_CHECKING:  # avoid circular import at runtime
    from agents.site_audit import PageReport

logger = logging.getLogger(__name__)


# Stop words for English + Swedish — the audit is used in both markets.
STOP_WORDS: set = {
    # English
    "the", "and", "for", "are", "but", "not", "you", "all", "can", "her",
    "was", "one", "our", "out", "day", "get", "has", "him", "his", "how",
    "man", "new", "now", "old", "see", "two", "way", "who", "boy", "did",
    "its", "let", "put", "say", "she", "too", "use", "with", "from", "this",
    "that", "have", "been", "were", "will", "when", "what", "your", "they",
    "them", "their", "would", "there", "could", "about", "which", "than",
    "into", "more", "some", "also", "such", "only", "very", "just", "like",
    "page", "site", "website", "home", "click", "here", "read",
    # Swedish
    "och", "att", "det", "som", "för", "med", "har", "inte", "den", "till",
    "men", "var", "ett", "vi", "du", "kan", "ska", "skulle", "blir", "blev",
    "vara", "är", "hos", "från", "ut", "om", "när", "så", "av", "på",
    "vid", "alla", "andra", "denna", "deras", "detta", "dom", "även",
    "eller", "ena", "enligt", "ena", "ena", "haft", "hade", "han", "hon",
    "hans", "hela", "henne", "hennes", "honom", "huvud", "här", "innan",
    "inom", "kunde", "många", "mig", "min", "mina", "mot", "ni", "när",
    "olika", "samma", "sig", "sin", "sina", "sitta", "själv", "sju",
    "skall", "sluta", "sju", "skulle", "som", "tar", "ta", "tio", "tre",
    "tva", "två", "vad", "vad", "varför", "varifrån", "varje", "varför",
    "vart", "vem", "vilka", "vilken", "vilket", "viss", "vore", "ändå",
    "över",
}


class KeywordOpportunityAgent:
    """Extract current keyword targeting and produce opportunity suggestions.

    The agent is called from SiteAuditAgent after crawling the site, so it
    reuses the already-fetched HTML rather than re-crawling. All external
    calls degrade gracefully: if ValueSERP isn't configured we skip SERP
    enrichment; if Anthropic isn't configured we use a deterministic
    template-based suggestion list.
    """

    def __init__(self, tenant_config: Any = None):
        self.tenant_config = tenant_config
        self.brand_name = (getattr(tenant_config, "brand_name", None) or "Brand")
        self.competitors: List[str] = list(
            getattr(tenant_config, "competitors", []) or []
        )
        self.serp_key = settings.VALUESERP_API_KEY
        self.anthropic_key = (
            getattr(tenant_config, "anthropic_api_key", None)
            or settings.ANTHROPIC_API_KEY
        )

    # ── Public entry point ──────────────────────────────────────────────────

    async def build(
        self,
        host: str,
        base_url: str,
        pages: List["PageReport"],
        client: Optional[httpx.AsyncClient] = None,
    ) -> Dict[str, Any]:
        # Step 1: extract what the site already targets.
        current_keywords = self._extract_current_keywords(pages)
        primary_seed = current_keywords[0]["phrase"] if current_keywords else self.brand_name

        # Step 2: pull SERP signal for the primary seed in parallel with the
        # LLM suggestion call. Both are best-effort and have safe fallbacks.
        related_task = self._related_searches(primary_seed, client)
        suggestions_task = self._llm_suggestions(host, current_keywords)
        competitor_task = self._competitor_gap(current_keywords, client)

        related, suggestions, competitor_gap = await asyncio.gather(
            related_task, suggestions_task, competitor_task,
            return_exceptions=False,
        )

        # Step 3: map each opportunity to the closest existing page (or
        # flag "new page needed"). This is a simple lexical match — close
        # enough to help users start, and dashboard users can override.
        opportunities = self._map_to_pages(suggestions, pages, base_url)

        # Step 4: cluster opportunities into pillar + supporting groups.
        clusters = self._cluster(opportunities)

        return {
            "current_keywords": current_keywords[:25],
            "opportunities": opportunities[:30],
            "clusters": clusters,
            "competitor_gap": competitor_gap,
            "related_searches": related,
            "primary_seed": primary_seed,
        }

    # ── Step 1: current keyword extraction ──────────────────────────────────

    def _extract_current_keywords(
        self, pages: List["PageReport"]
    ) -> List[Dict[str, Any]]:
        """Phrase frequency across titles, H1/H2 and a body sample, weighted
        to favour phrases that appear in headings (those are the page's
        explicit topic signals, not just incidental body words).
        """
        # phrase -> (score, [urls])
        scored: Dict[str, Tuple[float, List[str]]] = {}

        def _bump(phrase: str, weight: float, url: str) -> None:
            phrase = phrase.strip().lower()
            if not phrase or len(phrase) < 4 or len(phrase) > 60:
                return
            # Drop phrases that are entirely stop-words.
            words = re.findall(r"\b\w+\b", phrase)
            if not words or all(w in STOP_WORDS for w in words):
                return
            cur_score, urls = scored.get(phrase, (0.0, []))
            cur_score += weight
            if url not in urls:
                urls.append(url)
            scored[phrase] = (cur_score, urls)

        for p in pages:
            url = p.url
            # Title — strong signal but often includes brand name; we bump
            # down brand-only phrases later.
            if p.title:
                for ph in self._candidate_phrases(p.title):
                    _bump(ph, 3.0, url)
            if p.h1_text:
                for ph in self._candidate_phrases(p.h1_text):
                    _bump(ph, 2.5, url)
            for h2 in p.h2_texts:
                for ph in self._candidate_phrases(h2):
                    _bump(ph, 1.5, url)
            if p.meta_description:
                for ph in self._candidate_phrases(p.meta_description):
                    _bump(ph, 1.0, url)
            body = getattr(p, "body_text_sample", None)
            if body:
                for ph in self._candidate_phrases(body, max_phrases=40):
                    _bump(ph, 0.4, url)

        # De-prioritise phrases that are just the brand name.
        brand_lower = self.brand_name.lower()
        out: List[Dict[str, Any]] = []
        for phrase, (score, urls) in scored.items():
            if phrase == brand_lower:
                continue
            out.append({
                "phrase": phrase,
                "score": round(score, 2),
                "pages": urls[:5],
                "page_count": len(urls),
            })
        out.sort(key=lambda k: k["score"], reverse=True)
        return out

    def _candidate_phrases(self, text: str, max_phrases: int = 12) -> List[str]:
        """Generate 2- and 3-grams from text, dropping stop-only phrases."""
        text = re.sub(r"[^\w\s\-]", " ", text or "").lower()
        tokens = [t for t in re.split(r"\s+", text) if t]
        if not tokens:
            return []
        candidates: List[str] = []
        for n in (3, 2):
            for i in range(len(tokens) - n + 1):
                window = tokens[i:i + n]
                # Reject if first or last token is a stop word; "best crm"
                # is fine, "the best" is not.
                if window[0] in STOP_WORDS or window[-1] in STOP_WORDS:
                    continue
                if all(len(w) <= 2 for w in window):
                    continue
                candidates.append(" ".join(window))
        # Keep most-frequent candidates (rough TF).
        counts = Counter(candidates)
        return [phrase for phrase, _ in counts.most_common(max_phrases)]

    # ── Step 2a: SERP related searches ──────────────────────────────────────

    async def _related_searches(
        self, query: str, client: Optional[httpx.AsyncClient]
    ) -> List[str]:
        if not self.serp_key or not query:
            return []
        owned_client = client is None
        if owned_client:
            client = httpx.AsyncClient(timeout=15.0)
        try:
            resp = await client.get(
                "https://api.valueserp.com/search",
                params={
                    "api_key": self.serp_key,
                    "q": query,
                    "google_domain": "google.com",
                    "num": 10,
                },
            )
            if resp.status_code != 200:
                return []
            data = resp.json() or {}
            related = data.get("related_searches") or []
            # ValueSERP returns objects; accept either string or {query: ...}.
            out: List[str] = []
            for r in related:
                if isinstance(r, str):
                    out.append(r)
                elif isinstance(r, dict) and r.get("query"):
                    out.append(str(r["query"]))
            paa = data.get("related_questions") or []
            for q in paa:
                if isinstance(q, dict) and q.get("question"):
                    out.append(str(q["question"]))
            # De-dupe preserving order.
            seen: set = set()
            result: List[str] = []
            for item in out:
                key = item.strip().lower()
                if key and key not in seen:
                    seen.add(key)
                    result.append(item.strip())
            return result[:15]
        except Exception as e:
            logger.info(f"valueserp related_searches failed for {query!r}: {e}")
            return []
        finally:
            if owned_client:
                await client.aclose()

    # ── Step 2b: LLM suggestions ────────────────────────────────────────────

    async def _llm_suggestions(
        self, host: str, current_keywords: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        if not self.anthropic_key:
            return self._fallback_suggestions(host, current_keywords)
        try:
            from anthropic import Anthropic
        except Exception:
            return self._fallback_suggestions(host, current_keywords)

        # Build a compact context for the LLM. We include the top 12 already-
        # targeted phrases so the suggestions are adjacent (long-tail
        # extensions and related intents) rather than wholly off-topic.
        existing = ", ".join(k["phrase"] for k in current_keywords[:12]) or "(none extracted)"
        usp = audience = description = ""
        if self.tenant_config and hasattr(self.tenant_config, "get_raw"):
            usp = (self.tenant_config.get_raw("unique_selling_points") or "").strip()
            audience = (self.tenant_config.get_raw("target_audience") or "").strip()
            description = (self.tenant_config.get_raw("brand_description") or "").strip()
        comps = ", ".join(self.competitors[:6]) or "(none provided)"

        prompt = f"""You are an SEO strategist. Analyse this site and propose 20 keyword opportunities the brand could realistically rank for to grow organic and AI-assistant traffic.

Brand: {self.brand_name}
Domain: {host}
Brand description: {description or "—"}
Target audience: {audience or "—"}
USP: {usp or "—"}
Known competitors: {comps}
Phrases the site already targets: {existing}

For each opportunity output a JSON object with these fields:
  - keyword (string, the search query, lowercase, 2–6 words)
  - intent ("informational" | "commercial" | "transactional" | "navigational")
  - difficulty ("low" | "medium" | "high")  // gut estimate
  - reasoning (≤ 18 words explaining why this is winnable)
  - is_long_tail (true | false)

Mix the 20 across:
  - 10 long-tail informational ("how to", "what is", "guide", question forms)
  - 5 commercial-investigation ("best", "vs", "alternative", "for [audience]")
  - 3 transactional ("pricing", "buy", "demo", "free trial")
  - 2 stretch terms (higher difficulty but high commercial value)

Avoid duplicates of phrases the site already targets unless extending into a long-tail variant. Output ONLY a JSON array — no prose, no markdown fences."""

        def _call() -> str:
            client = Anthropic(api_key=self.anthropic_key)
            msg = client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=2200,
                messages=[{"role": "user", "content": prompt}],
            )
            return msg.content[0].text or ""

        try:
            text = await asyncio.to_thread(_call)
        except Exception as e:
            logger.info(f"keyword_opportunity LLM call failed: {e}")
            return self._fallback_suggestions(host, current_keywords)

        text = re.sub(r"^```(?:json)?|```$", "", text.strip(), flags=re.MULTILINE).strip()
        try:
            data = json.loads(text)
        except Exception:
            logger.info("keyword_opportunity LLM returned non-JSON; falling back.")
            return self._fallback_suggestions(host, current_keywords)
        if not isinstance(data, list):
            return self._fallback_suggestions(host, current_keywords)

        out: List[Dict[str, Any]] = []
        for item in data:
            if not isinstance(item, dict):
                continue
            kw = str(item.get("keyword") or "").strip().lower()
            if not kw:
                continue
            out.append({
                "keyword": kw,
                "intent": str(item.get("intent") or "informational"),
                "difficulty": str(item.get("difficulty") or "medium"),
                "reasoning": str(item.get("reasoning") or "").strip(),
                "is_long_tail": bool(item.get("is_long_tail", True)),
            })
        return out

    def _fallback_suggestions(
        self, host: str, current_keywords: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """Deterministic suggestion set when no LLM is available. Builds
        long-tail variants from the already-extracted phrases."""
        seeds = [k["phrase"] for k in current_keywords[:6]] or [self.brand_name.lower()]
        templates_info = [
            ("how to use {seed}", "informational", "low"),
            ("what is {seed}", "informational", "low"),
            ("{seed} guide", "informational", "low"),
            ("{seed} examples", "informational", "low"),
            ("{seed} checklist", "informational", "low"),
        ]
        templates_comm = [
            ("best {seed} tools", "commercial", "medium"),
            ("{seed} for small business", "commercial", "medium"),
            ("{seed} alternatives", "commercial", "medium"),
        ]
        templates_trans = [
            ("{seed} pricing", "transactional", "medium"),
            ("{seed} free trial", "transactional", "low"),
        ]
        out: List[Dict[str, Any]] = []
        for seed in seeds[:4]:
            for tpl, intent, diff in templates_info + templates_comm + templates_trans:
                out.append({
                    "keyword": tpl.format(seed=seed),
                    "intent": intent,
                    "difficulty": diff,
                    "reasoning": "Long-tail extension of an existing topic on the site.",
                    "is_long_tail": True,
                })
        # De-dupe and trim.
        seen: set = set()
        deduped: List[Dict[str, Any]] = []
        for o in out:
            if o["keyword"] in seen:
                continue
            seen.add(o["keyword"])
            deduped.append(o)
        return deduped[:20]

    # ── Step 3: map suggestions to existing pages ───────────────────────────

    def _map_to_pages(
        self, suggestions: List[Dict[str, Any]], pages: List["PageReport"],
        base_url: str,
    ) -> List[Dict[str, Any]]:
        """Lexical token-overlap match: for each suggestion, score every
        page by how many keyword tokens appear in title+H1+H2; pick best.
        """
        page_index: List[Tuple[str, set]] = []
        for p in pages:
            tokens = set()
            for chunk in (p.title, p.h1_text, " ".join(p.h2_texts)):
                if not chunk:
                    continue
                for t in re.findall(r"\b\w+\b", chunk.lower()):
                    if t not in STOP_WORDS and len(t) > 2:
                        tokens.add(t)
            page_index.append((p.url, tokens))

        out: List[Dict[str, Any]] = []
        for s in suggestions:
            kw_tokens = {
                t for t in re.findall(r"\b\w+\b", s["keyword"])
                if t not in STOP_WORDS and len(t) > 2
            }
            best_url: Optional[str] = None
            best_score = 0
            for url, tokens in page_index:
                overlap = len(kw_tokens & tokens)
                if overlap > best_score:
                    best_score = overlap
                    best_url = url
            mapped = dict(s)
            if best_url and best_score >= max(1, len(kw_tokens) // 2):
                mapped["target_url"] = best_url
                mapped["target_status"] = "existing_page"
                mapped["target_note"] = (
                    "Refresh this page to target the keyword in the title, H1, and first paragraph."
                )
            else:
                mapped["target_url"] = None
                mapped["target_status"] = "new_page_needed"
                mapped["target_note"] = (
                    "No existing page is a strong match — plan a new piece of content for this keyword."
                )
            out.append(mapped)
        return out

    # ── Step 4: cluster ─────────────────────────────────────────────────────

    def _cluster(self, opportunities: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Cluster keywords by their first non-stop token. Crude but useful
        as a starting point — users can re-organise in the dashboard."""
        buckets: Dict[str, List[Dict[str, Any]]] = {}
        for o in opportunities:
            tokens = [
                t for t in re.findall(r"\b\w+\b", o["keyword"])
                if t not in STOP_WORDS and len(t) > 2
            ]
            head = tokens[0] if tokens else "general"
            buckets.setdefault(head, []).append(o)
        clusters: List[Dict[str, Any]] = []
        for head, items in buckets.items():
            if len(items) < 2:
                continue
            # Pick the broadest (shortest) keyword as the pillar candidate.
            items.sort(key=lambda x: len(x["keyword"]))
            pillar = items[0]["keyword"]
            supporting = [i["keyword"] for i in items[1:]]
            clusters.append({
                "pillar": pillar,
                "head_term": head,
                "supporting": supporting,
                "size": len(items),
            })
        clusters.sort(key=lambda c: c["size"], reverse=True)
        return clusters[:8]

    # ── Optional: competitor gap ────────────────────────────────────────────

    async def _competitor_gap(
        self, current_keywords: List[Dict[str, Any]],
        client: Optional[httpx.AsyncClient],
    ) -> List[Dict[str, Any]]:
        """For each top current keyword, check if a competitor outranks us
        in Google. We don't have the brand's ranking from this audit, but we
        DO have the competitor list — so we report which keywords have at
        least one competitor in the top 10. The dashboard frames these as
        "competitor opportunity zones" the brand could attack.
        """
        if not self.serp_key or not self.competitors or not current_keywords:
            return []
        owned_client = client is None
        if owned_client:
            client = httpx.AsyncClient(timeout=15.0)
        gaps: List[Dict[str, Any]] = []
        try:
            for kw in current_keywords[:5]:  # bound API spend
                phrase = kw["phrase"]
                try:
                    resp = await client.get(
                        "https://api.valueserp.com/search",
                        params={
                            "api_key": self.serp_key,
                            "q": phrase,
                            "google_domain": "google.com",
                            "num": 10,
                        },
                    )
                    if resp.status_code != 200:
                        continue
                    data = resp.json() or {}
                except Exception as e:
                    logger.info(f"valueserp competitor probe failed for {phrase!r}: {e}")
                    continue
                organic = (data.get("organic_results") or [])[:10]
                comps_in_top10: List[str] = []
                for r in organic:
                    link = (r.get("link") or "").lower()
                    domain = urlparse(link).hostname or ""
                    domain = domain.lstrip("www.")
                    for c in self.competitors:
                        if c and c.lower().lstrip("www.") in domain:
                            if c not in comps_in_top10:
                                comps_in_top10.append(c)
                if comps_in_top10:
                    gaps.append({
                        "keyword": phrase,
                        "competitors_in_top10": comps_in_top10,
                        "note": (
                            f"{len(comps_in_top10)} of your competitors rank in Google's top 10 for this keyword — "
                            "a content refresh + backlinks campaign can close the gap."
                        ),
                    })
        finally:
            if owned_client:
                await client.aclose()
        return gaps
